export const cross = {
  light: '┼',
  heavy: '╋',
  double: '╬',
  lightVerticalHeavyHorizontal: '┿',
  heavyVerticalLightHorizontal: '╂',
  leftHeavyRightVerticalLight: '┽',
  rightHeavyLeftVerticalLight: '┾',
  upHeavyDownHorizontalLight: '╀',
  downHeavyUpHorizontalLight: '╁',
  leftUpHeavyRightDownLight: '╃',
  rightUpHeavyLeftDownLight: '╄',
  leftDownHeavyRightUpLight: '╅',
  rightDownHeavyLeftUpLight: '╆',
  downLightUpHorizontalHeavy: '╇',
  upLightDownHorizontalHeavy: '╈',
  rightLightLeftVerticalHeavy: '╉',
  leftLightRightVerticalHeavy: '╊',
  singleVerticalDoubleHorizontal: '╪',
  doubleVerticalSingleHorizontal: '╫'
} as const;
